### ISSUE TITLE
Discord message behavior improvements

### ISSUE THREAD

**Issue by bbrucee** [griffv/griffv.github.io#9]
## Describe the issues
The Discord chat box has some weird behaviors that should be fixed if we want to use this on the site

- A: Empty message submit
- B: Curse words aren't filtered
- C: Message box doesn't clear after sending

## A: To Reproduce
1. Submit an empty text box

## Expected behavior
Nothing happens, instead we get a link to an error message
![Animation_5](https://user-images.githubusercontent.com/13605787/121454158-51279200-c970-11eb-9794-5358683418e7.gif)

## B: To Reproduce
1. Submit a curse word

## Expected behavior
Nothing happens or an error message, no hate speech!

## C: To Reproduce
1. Submit any message

## Expected behavior
Message box should clear so user knows that the message has been sent and doesn't double send anything
![Animation_6](https://user-images.githubusercontent.com/13605787/121454415-bb403700-c970-11eb-9b81-565982783e8a.gif)
Pressed enter once, clicked submit once. Discord bot sent message twice.

**Comment by Rickymista** [comment]
https://github.com/griffv/griffv.github.io/pull/10 has been created to address these issues.
